### ISSUE TITLE
Can't start it with node app.js

### ISSUE THREAD

**Issue by Vr3xX** [dftd/codwatcher#1]
root@vps-eee042a6:/data/myserver/bot# node app.js
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'discord.js'
Require stack:
- /data/myserver/bot/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/data/myserver/bot/app.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/data/myserver/bot/app.js' ]

**Comment by Vr3xX** [comment]
it's looking for a discord.js, which is not given with indicated files

**Comment by patriksh** [comment]
@Vr3xX you're supposed to run `npm i` to install the required modules.

**Comment by Vr3xX** [comment]
i did, it throws out this

npm ERR! Cannot read property 'insert' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-01-30T17_45_36_555Z-debug-0.log

**Comment by Vr3xX** [comment]
I updated my node to latest version, as suggestion show it might be the error

Now the error shows this on npm i

root@vps-eee042a6:/data/myserver/bot# npm i
node:internal/modules/cjs/loader:1060
  const err = new Error(message);
              ^

Error: Cannot find module 'semver'
Require stack:
- /usr/share/nodejs/npm/lib/utils/unsupported.js
- /usr/share/nodejs/npm/lib/cli.js
- /usr/share/nodejs/npm/bin/npm-cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1060:15)
    at Module._load (node:internal/modules/cjs/loader:905:27)
    at Module.require (node:internal/modules/cjs/loader:1127:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (/usr/share/nodejs/npm/lib/utils/unsupported.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1246:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Module._load (node:internal/modules/cjs/loader:942:12)
    at Module.require (node:internal/modules/cjs/loader:1127:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/share/nodejs/npm/lib/utils/unsupported.js',
    '/usr/share/nodejs/npm/lib/cli.js',
    '/usr/share/nodejs/npm/bin/npm-cli.js'
  ]
}

Node.js v19.5.0

**Comment by patriksh** [comment]
This seems like an issue with your node installation. Try reconnecting to your SSH, or reinstalling node as whole.

**Comment by Vr3xX** [comment]
what requirement should my node version be on, it is on v 19, should it be lower, as it says unsupported

**Comment by Vr3xX** [comment]
Ok it's fixed now, by changing the version and rebuilding the files. Thanks for help

**Comment by patriksh** [comment]
@Vr3xX I was just about to reply that I use v16.19.0. Glad you got it sorted out.
