### ISSUE TITLE
Bot works for 10 seconds

### ISSUE THREAD

**Issue by Vr3xX** [dftd/codwatcher#2]
So everything worked fine, said bot online, then crashed with theses errors

Bot is online.
Error: Failed all 3 attempts
    at QueryRunner.run (/data/myserver/bot/node_modules/gamedig/lib/QueryRunner.js:95:21)
    at async Gamedig.query (/data/myserver/bot/node_modules/gamedig/lib/index.js:11:16)
    at async Gamedig.query (/data/myserver/bot/node_modules/gamedig/lib/index.js:19:16)
    at async module.exports.query (/data/myserver/bot/helper.js:14:16)
    at async /data/myserver/bot/helper.js:37:22
Attempt #1 - Port=28962 Retry=0:
Error: UDP - Timed out after 3000ms
    at Timeout.<anonymous> (/data/myserver/bot/node_modules/gamedig/lib/Promises.js:7:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
Attempt #2 - Port=28962 Retry=1:
Error: UDP - Timed out after 3000ms
    at Timeout.<anonymous> (/data/myserver/bot/node_modules/gamedig/lib/Promises.js:7:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
Attempt #3 - Port=28962 Retry=2:
Error: UDP - Timed out after 3000ms
    at Timeout.<anonymous> (/data/myserver/bot/node_modules/gamedig/lib/Promises.js:7:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
Error: Failed all 3 attempts
    at QueryRunner.run (/data/myserver/bot/node_modules/gamedig/lib/QueryRunner.js:95:21)
    at async Gamedig.query (/data/myserver/bot/node_modules/gamedig/lib/index.js:11:16)
    at async Gamedig.query (/data/myserver/bot/node_modules/gamedig/lib/index.js:19:16)
    at async module.exports.query (/data/myserver/bot/helper.js:14:16)
    at async /data/myserver/bot/helper.js:37:22
Attempt #1 - Port=28962 Retry=0:
Error: UDP - Timed out after 3000ms
    at Timeout.<anonymous> (/data/myserver/bot/node_modules/gamedig/lib/Promises.js:7:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
Attempt #2 - Port=28962 Retry=1:
Error: UDP - Timed out after 3000ms
    at Timeout.<anonymous> (/data/myserver/bot/node_modules/gamedig/lib/Promises.js:7:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
Attempt #3 - Port=28962 Retry=2:
Error: UDP - Timed out after 3000ms
    at Timeout.<anonymous> (/data/myserver/bot/node_modules/gamedig/lib/Promises.js:7:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
Error: Failed all 3 attempts
    at QueryRunner.run (/data/myserver/bot/node_modules/gamedig/lib/QueryRunner.js:95:21)
    at async Gamedig.query (/data/myserver/bot/node_modules/gamedig/lib/index.js:11:16)
    at async Gamedig.query (/data/myserver/bot/node_modules/gamedig/lib/index.js:19:16)
    at async module.exports.query (/data/myserver/bot/helper.js:14:16)
    at async /data/myserver/bot/helper.js:37:22
Attempt #1 - Port=28962 Retry=0:
Error: UDP - Timed out after 3000ms
    at Timeout.<anonymous> (/data/myserver/bot/node_modules/gamedig/lib/Promises.js:7:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
Attempt #2 - Port=28962 Retry=1:
Error: UDP - Timed out after 3000ms
    at Timeout.<anonymous> (/data/myserver/bot/node_modules/gamedig/lib/Promises.js:7:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
Attempt #3 - Port=28962 Retry=2:
Error: UDP - Timed out after 3000ms
    at Timeout.<anonymous> (/data/myserver/bot/node_modules/gamedig/lib/Promises.js:7:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)

**Comment by patriksh** [comment]
Either your IP/port configuration for the gameserver is wrong, or a firewall is blocking `getstatus` requests .

**Comment by Vr3xX** [comment]
my ip and port looks good, as it worked for server. But it lists the second server port. Q, do you add multiple servers on that one script only, or should I make seperate for each server?

**Comment by patriksh** [comment]
You can define multiple servers, see how in the sample [config.json](https://github.com/patriksh/codwatcher/blob/main/bot/config.json) there's a SD and a DM server.

**Comment by Vr3xX** [comment]
I fixed it, strangely, i just restarted my servers, now its fine. Weird
